export const CurrencyArray = [
  { code: "AED", symbol: "د.إ", name: "United Arab Emirates Dirham", countryCode: "ae" },
  { code: "AFN", symbol: "؋", name: "Afghan Afghani", countryCode: "af" },
  { code: "ALL", symbol: "L", name: "Albanian Lek", countryCode: "al" },
  { code: "AMD", symbol: "֏", name: "Armenian Dram", countryCode: "am" },
  { code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder", countryCode: "cw" },
  { code: "AOA", symbol: "Kz", name: "Angolan Kwanza", countryCode: "ao" },
  { code: "ARS", symbol: "$", name: "Argentine Peso", countryCode: "ar" },
  { code: "AUD", symbol: "$", name: "Australian Dollar", countryCode: "au" },
  { code: "AWG", symbol: "ƒ", name: "Aruban Florin", countryCode: "aw" },
  { code: "AZN", symbol: "₼", name: "Azerbaijani Manat", countryCode: "az" },
  { code: "BAM", symbol: "KM", name: "Bosnia-Herzegovina Convertible Mark", countryCode: "ba" },
  { code: "BBD", symbol: "$", name: "Barbadian Dollar", countryCode: "bb" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka", countryCode: "bd" },
  { code: "BGN", symbol: "лв", name: "Bulgarian Lev", countryCode: "bg" },
  { code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar", countryCode: "bh" },
  { code: "BIF", symbol: "FBu", name: "Burundian Franc", countryCode: "bi" },
  { code: "BMD", symbol: "$", name: "Bermudian Dollar", countryCode: "bm" },
  { code: "BND", symbol: "$", name: "Brunei Dollar", countryCode: "bn" },
  { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano", countryCode: "bo" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real", countryCode: "br" },
  { code: "BSD", symbol: "$", name: "Bahamian Dollar", countryCode: "bs" },
  { code: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum", countryCode: "bt" },
  { code: "BWP", symbol: "P", name: "Botswana Pula", countryCode: "bw" },
  { code: "BYN", symbol: "Br", name: "Belarusian Ruble", countryCode: "by" },
  { code: "BZD", symbol: "$", name: "Belize Dollar", countryCode: "bz" },
  { code: "CAD", symbol: "$", name: "Canadian Dollar", countryCode: "ca" },
  { code: "CDF", symbol: "FC", name: "Congolese Franc", countryCode: "cd" },
  { code: "CHF", symbol: "Fr.", name: "Swiss Franc", countryCode: "ch" },
  { code: "CLP", symbol: "$", name: "Chilean Peso", countryCode: "cl" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan", countryCode: "cn" },
  { code: "COP", symbol: "$", name: "Colombian Peso", countryCode: "co" },
  { code: "CRC", symbol: "₡", name: "Costa Rican Colón", countryCode: "cr" },
  { code: "CUP", symbol: "$", name: "Cuban Peso", countryCode: "cu" },
  { code: "CVE", symbol: "$", name: "Cape Verdean Escudo", countryCode: "cv" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna", countryCode: "cz" },
  { code: "DJF", symbol: "Fdj", name: "Djiboutian Franc", countryCode: "dj" },
  { code: "DKK", symbol: "kr", name: "Danish Krone", countryCode: "dk" },
  { code: "DOP", symbol: "$", name: "Dominican Peso", countryCode: "do" },
  { code: "DZD", symbol: "د.ج", name: "Algerian Dinar", countryCode: "dz" },
  { code: "EGP", symbol: "£", name: "Egyptian Pound", countryCode: "eg" },
  { code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa", countryCode: "er" },
  { code: "ETB", symbol: "Br", name: "Ethiopian Birr", countryCode: "et" },
  { code: "EUR", symbol: "€", name: "Euro", countryCode: "eu" },
  { code: "FJD", symbol: "$", name: "Fijian Dollar", countryCode: "fj" },
  { code: "FKP", symbol: "£", name: "Falkland Islands Pound", countryCode: "fk" },
  { code: "FOK", symbol: "kr", name: "Faroese Króna", countryCode: "fo" },
  { code: "GBP", symbol: "£", name: "British Pound Sterling", countryCode: "gb" },
  { code: "GEL", symbol: "₾", name: "Georgian Lari", countryCode: "ge" },
  { code: "GGP", symbol: "£", name: "Guernsey Pound", countryCode: "gg" },
  { code: "GHS", symbol: "₵", name: "Ghanaian Cedi", countryCode: "gh" },
  { code: "GIP", symbol: "£", name: "Gibraltar Pound", countryCode: "gi" },
  { code: "GMD", symbol: "D", name: "Gambian Dalasi", countryCode: "gm" },
  { code: "GNF", symbol: "FG", name: "Guinean Franc", countryCode: "gn" },
  { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal", countryCode: "gt" },
  { code: "GYD", symbol: "$", name: "Guyanese Dollar", countryCode: "gy" },
  { code: "HKD", symbol: "$", name: "Hong Kong Dollar", countryCode: "hk" },
  { code: "HNL", symbol: "L", name: "Honduran Lempira", countryCode: "hn" },
  { code: "HRK", symbol: "kn", name: "Croatian Kuna", countryCode: "hr" },
  { code: "HTG", symbol: "G", name: "Haitian Gourde", countryCode: "ht" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint", countryCode: "hu" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah", countryCode: "id" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel", countryCode: "il" },
  { code: "INR", symbol: "₹", name: "Indian Rupee", countryCode: "in" },
  { code: "IQD", symbol: "ع.د", name: "Iraqi Dinar", countryCode: "iq" },
  { code: "IRR", symbol: "﷼", name: "Iranian Rial", countryCode: "ir" },
  { code: "ISK", symbol: "kr", name: "Icelandic Króna", countryCode: "is" },
  { code: "JMD", symbol: "$", name: "Jamaican Dollar", countryCode: "jm" },
  { code: "JOD", symbol: "د.ا", name: "Jordanian Dinar", countryCode: "jo" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen", countryCode: "jp" },
  { code: "KES", symbol: "KSh", name: "Kenyan Shilling", countryCode: "ke" },
  { code: "KGS", symbol: "лв", name: "Kyrgyzstani Som", countryCode: "kg" },
  { code: "KHR", symbol: "៛", name: "Cambodian Riel", countryCode: "kh" },
  { code: "KRW", symbol: "₩", name: "South Korean Won", countryCode: "kr" },
  { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar", countryCode: "kw" },
  { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge", countryCode: "kz" },
  { code: "LAK", symbol: "₭", name: "Lao Kip", countryCode: "la" },
  { code: "LBP", symbol: "ل.ل", name: "Lebanese Pound", countryCode: "lb" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee", countryCode: "lk" },
  { code: "LRD", symbol: "$", name: "Liberian Dollar", countryCode: "lr" },
  { code: "LSL", symbol: "L", name: "Lesotho Loti", countryCode: "ls" },
  { code: "LYD", symbol: "ل.د", name: "Libyan Dinar", countryCode: "ly" },
  { code: "MAD", symbol: "د.م.", name: "Moroccan Dirham", countryCode: "ma" },
  { code: "MDL", symbol: "L", name: "Moldovan Leu", countryCode: "md" },
  { code: "MGA", symbol: "Ar", name: "Malagasy Ariary", countryCode: "mg" },
  { code: "MKD", symbol: "ден", name: "Macedonian Denar", countryCode: "mk" },
  { code: "MMK", symbol: "K", name: "Myanmar Kyat", countryCode: "mm" },
  { code: "MNT", symbol: "₮", name: "Mongolian Tögrög", countryCode: "mn" },
  { code: "MOP", symbol: "P", name: "Macanese Pataca", countryCode: "mo" },
  { code: "MUR", symbol: "₨", name: "Mauritian Rupee", countryCode: "mu" },
  { code: "MVR", symbol: "Rf", name: "Maldivian Rufiyaa", countryCode: "mv" },
  { code: "MWK", symbol: "MK", name: "Malawian Kwacha", countryCode: "mw" },
  { code: "MXN", symbol: "$", name: "Mexican Peso", countryCode: "mx" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit", countryCode: "my" },
  { code: "MZN", symbol: "MT", name: "Mozambican Metical", countryCode: "mz" },
  { code: "NAD", symbol: "$", name: "Namibian Dollar", countryCode: "na" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira", countryCode: "ng" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone", countryCode: "no" },
  { code: "NPR", symbol: "₨", name: "Nepalese Rupee", countryCode: "np" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar", countryCode: "nz" },
  { code: "OMR", symbol: "ر.ع.", name: "Omani Rial", countryCode: "om" },
  { code: "PAB", symbol: "B/.", name: "Panamanian Balboa", countryCode: "pa" },
  { code: "PEN", symbol: "S/.", name: "Peruvian Sol", countryCode: "pe" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso", countryCode: "ph" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee", countryCode: "pk" },
  { code: "PLN", symbol: "zł", name: "Polish Zloty", countryCode: "pl" },
  { code: "QAR", symbol: "ر.ق", name: "Qatari Riyal", countryCode: "qa" },
  { code: "RON", symbol: "lei", name: "Romanian Leu", countryCode: "ro" },
  { code: "RSD", symbol: "дин.", name: "Serbian Dinar", countryCode: "rs" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble", countryCode: "ru" },
  { code: "SAR", symbol: "ر.س", name: "Saudi Riyal", countryCode: "sa" },
  { code: "SBD", symbol: "$", name: "Solomon Islands Dollar", countryCode: "sb" },
  { code: "SCR", symbol: "₨", name: "Seychellois Rupee", countryCode: "sc" },
  { code: "SDG", symbol: "ج.س.", name: "Sudanese Pound", countryCode: "sd" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona", countryCode: "se" },
  { code: "SGD", symbol: "$", name: "Singapore Dollar", countryCode: "sg" },
  { code: "SHP", symbol: "£", name: "Saint Helena Pound", countryCode: "sh" },
  { code: "SLL", symbol: "Le", name: "Sierra Leonean Leone", countryCode: "sl" },
  { code: "SOS", symbol: "Sh", name: "Somali Shilling", countryCode: "so" },
  { code: "SRD", symbol: "$", name: "Surinamese Dollar", countryCode: "sr" },
  { code: "SSP", symbol: "£", name: "South Sudanese Pound", countryCode: "ss" },
  { code: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra", countryCode: "st" },
  { code: "SYP", symbol: "ل.س", name: "Syrian Pound", countryCode: "sy" },
  { code: "SZL", symbol: "L", name: "Swazi Lilangeni", countryCode: "sz" },
  { code: "THB", symbol: "฿", name: "Thai Baht", countryCode: "th" },
  { code: "TJS", symbol: "ЅМ", name: "Tajikistani Somoni", countryCode: "tj" },
  { code: "TMT", symbol: "m", name: "Turkmenistani Manat", countryCode: "tm" },
  { code: "TND", symbol: "د.ت", name: "Tunisian Dinar", countryCode: "tn" },
  { code: "TOP", symbol: "T$", name: "Tongan Paʻanga", countryCode: "to" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira", countryCode: "tr" },
  { code: "TTD", symbol: "$", name: "Trinidad and Tobago Dollar", countryCode: "tt" },
  { code: "TWD", symbol: "$", name: "New Taiwan Dollar", countryCode: "tw" },
  { code: "TZS", symbol: "Sh", name: "Tanzanian Shilling", countryCode: "tz" },
  { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia", countryCode: "ua" },
  { code: "UGX", symbol: "Sh", name: "Ugandan Shilling", countryCode: "ug" },
  { code: "UYU", symbol: "$", name: "Uruguayan Peso", countryCode: "uy" },
  { code: "UZS", symbol: "сум", name: "Uzbekistani Som", countryCode: "uz" },
  { code: "VEF", symbol: "Bs", name: "Venezuelan Bolívar", countryCode: "ve" },
  { code: "VND", symbol: "₫", name: "Vietnamese Dong", countryCode: "vn" },
  { code: "VUV", symbol: "Vt", name: "Vanuatu Vatu", countryCode: "vu" },
  { code: "WST", symbol: "T", name: "Samoan Tala", countryCode: "ws" },
  { code: "XAF", symbol: "FCFA", name: "CFA Franc", countryCode: "cm" },
  { code: "XAG", symbol: "oz", name: "Silver (1 oz)", countryCode: "international" },
  { code: "XAU", symbol: "oz", name: "Gold (1 oz)", countryCode: "international" },
  { code: "XBT", symbol: "BTC", name: "Bitcoin", countryCode: "international" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar", countryCode: "bb" },
  { code: "XOF", symbol: "FCFA", name: "CFA Franc", countryCode: "bf" },
  { code: "XPF", symbol: "₣", name: "CFP Franc", countryCode: "pf" },
  { code: "YER", symbol: "ر.ي", name: "Yemeni Rial", countryCode: "ye" },
  { code: "ZAR", symbol: "R", name: "South African Rand", countryCode: "za" },
  { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha", countryCode: "zm" },
  { code: "ZWL", symbol: "$", name: "Zimbabwean Dollar", countryCode: "zw" }
  
];
